name: graph-trackintel
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - fiona
  - gdal
  - geoalchemy2
  - geopandas>=0.9
  - matplotlib
  - networkx
  - numpy
  - osmnx
  - pandas
  - pint
  - psycopg2
  - pygeos>0.10
  - pyproj
  - rtree
  - scikit-learn
  - scipy
  - shapely
  - similaritymeasures
  - smopy
  - tqdm
  # tests
  - pytest
  - pytest-cov
  - pytest-xdist
  - pip
  - pip:
    - trackintel
    - powerlaw

