name: graph-trackintel
channels:
  - conda-forge
  - defaults
dependencies:
  - fiona=1.8.20
  - gdal=3.4.0
  - geoalchemy2
  - geopandas=0.10.2
  - matplotlib>=3.5.1
  - networkx>=2.7.1
  - numpy>=1.22.3
  - osmnx=1.1.2
  - pandas>=1.4.1
  - pint>=0.18
  - psycopg2>=2.9.3
  - pygeos=0.12.0
  - pyproj=3.3.0
  - python=3.10
  - rtree=0.9.7
  - scikit-learn
  - scipy>=1.8.0
  - shapely=1.8.0
  - similaritymeasures>=0.4.4
  - tqdm>=4.63.0
  # tests
  - pytest
  - pytest-cov
  - pytest-xdist
  - pip
  - pip:
    - trackintel==1.1.5

