name: test
channels:
  - conda-forge
dependencies:
- python=3.9
# required
- numpy
- scipy
- psycopg2
- networkx
- pyproj
- matplotlib
# tests
- pytest
- pytest-cov
- pytest-xdist
- pip:
  - trackintel
