# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # repeat every day

jobs:
  ubuntu-latest:
    name: ${{ matrix.os }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}   
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        env: 
          - environment.yml

      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python environment
      uses: conda-incubator/setup-miniconda@v2
      with:
          environment-file: ${{ matrix.env }}
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true
          
    - name: Check Environment
      run: |
        python -V
        python -c "import trackintel; trackintel.print_version();"
        conda info
    - name: Test with pytest
      run: |
        pytest -v -r s --color=yes --cov=trackintel --cov-append --cov-report term-missing --cov-report xml tests/
  
    - name: Codecov report
      uses: codecov/codecov-action@v1
